repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.4.0
        hooks:
        - id: trailing-whitespace
    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
        - id: black
          language_version: python3.7
    -   repo: local
        hooks:
        -   id: pylint
            name: pylint
            entry: pylint
            args: [
                "src"
            ]
            language: system
            types: [python]

    -   repo: local
        hooks:
        -   id: pytest
            name: Run tests using pytest
            entry: pytest
            args:
                [
                    "tests",
                    # "--junitxml=.junit/test-results.xml",
                    "--cov=src/pandas_transformers",
                    # "--cov-report=xml",
                    "--cov-report=html"
                ]
            language: system
            types: [python]
            stages: [commit]
            pass_filenames: false
            always_run: true



